# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

=begin
= 0.1 Version 0.1.
> 0.1 Any version higher than 0.1.
>= 0.1 Version 0.1 and any higher version.
< 0.1 Any version lower than 0.1.
<= 0.1 Version 0.1 and any lower version.
~> 0.1.2 Version 0.1.2 and the versions up to 0.2, not including 0.2. This operator works based on the last component that you specify in your version requirement. The example is equal to >= 0.1.2 combined with < 0.2.0 and will always match the latest known version matching your requirements.
~> 0 Version 0 and the versions up to 1, not including 1.
~> 0.1.3-beta.0 Beta and release versions for 0.1.3, release versions up to 0.2 excluding 0.2. Components separated by a dash (-) will not be considered for the version requirement.
=end

target 'iOSDemosOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSDemosOC
#  pod 'ESTabBarController-swift' # https://github.com/eggswift/ESTabBarController
  pod 'lottie-ios', '~> 4.5.1' # https://github.com/airbnb/lottie-ios
  pod 'SDWebImage', '~> 5.21.0' # https://github.com/SDWebImage/SDWebImage

end
